SET XACT_ABORT ON;
GO

BEGIN TRY
    BEGIN TRANSACTION;

    IF COL_LENGTH(N'social.SocialPosts', N'SimHash') IS NULL
        ALTER TABLE [social].[SocialPosts] ADD [SimHash] bigint NULL;

    IF COL_LENGTH(N'social.SocialComments', N'SimHash') IS NULL
        ALTER TABLE [social].[SocialComments] ADD [SimHash] bigint NULL;

    IF COL_LENGTH(N'social.ContentReports', N'IsAutoGenerated') IS NULL
        ALTER TABLE [social].[ContentReports] ADD [IsAutoGenerated] bit NOT NULL
            CONSTRAINT [DF_ContentReports_IsAutoGenerated] DEFAULT ((0));

    -- 系統自動送出的檢舉沒有真人檢舉人，ReporterUserId 改成可為 null 來表示；
    -- 既有的 FK_ContentReports_ReporterUser 不用動，FK 約束本來就允許 null。
    IF EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = N'social' AND TABLE_NAME = N'ContentReports'
          AND COLUMN_NAME = N'ReporterUserId' AND IS_NULLABLE = N'NO')
        ALTER TABLE [social].[ContentReports] ALTER COLUMN [ReporterUserId] uniqueidentifier NULL;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;
GO

SELECT
    N'db-v0.10.1' AS [DatabaseVersion],
    N'貼文/留言新增 SimHash 重複偵測指紋；檢舉表支援系統自動送出的檢舉（ReporterUserId 可為 null、新增 IsAutoGenerated）' AS [UpgradeResult];
GO
