-- 保留原本手動測試貼文與檢舉，另建立可展示待審、隱藏及駁回的審核紀錄。
DECLARE @moderationCases TABLE(PostId uniqueidentifier PRIMARY KEY,ReportId uniqueidentifier,AuthorId uniqueidentifier,ReporterId uniqueidentifier,Title nvarchar(150),Content nvarchar(max),ReportStatus nvarchar(20),CreatedAt datetime2(3));
INSERT @moderationCases
SELECT CONVERT(uniqueidentifier,HASHBYTES('MD5',N'QMAH-CONNECTED-MODERATION-POST:'+CONVERT(nvarchar(36),u.UserId))),
    CONVERT(uniqueidentifier,HASHBYTES('MD5',N'QMAH-CONNECTED-MODERATION-REPORT:'+CONVERT(nvarchar(36),u.UserId))),u.UserId,reporter.UserId,
    CASE WHEN u.Ordinal>20 THEN
        CASE u.Ordinal%4 WHEN 0 THEN N'看展時可以拍照嗎' WHEN 1 THEN N'青瓷的釉色怎麼看' WHEN 2 THEN N'有人也喜歡看銅鏡背面嗎' ELSE N'長卷要從哪一端開始看' END
    ELSE CASE u.Ordinal%4 WHEN 0 THEN N'低價出清，全部私訊談' WHEN 1 THEN N'限時搶購，錯過今天就沒了' WHEN 2 THEN N'一直發一直發，看到就回一下' ELSE N'幫我衝人氣，路過都留言' END END,
    CASE WHEN u.Ordinal>20 THEN
        CASE u.Ordinal%4 WHEN 0 THEN N'下次想把喜歡的細節記下來。'+NCHAR(10)+N'展場如果禁止攝影，我就帶小本子畫幾筆。'
        WHEN 1 THEN N'同樣叫青瓷，照片裡有些偏灰，有些偏綠。'+NCHAR(10)+N'大家會先看釉色，還是先看器形？'
        WHEN 2 THEN N'我最近看銅鏡都先翻到背面找紋樣。'+NCHAR(10)+N'有時候還沒看說明，就先被那圈圖案吸住了。'
        ELSE N'看長卷時常常來回拉了好幾次才找到剛才的細節。'+NCHAR(10)+N'有人會先看完整幅，再慢慢看局部嗎？' END
    ELSE CASE u.Ordinal%4 WHEN 0 THEN N'便宜賣便宜賣便宜賣，不用看內容，全部私訊報價。'
        WHEN 1 THEN N'搶購搶購搶購，今日最後一波，每篇都要推一次！'
        WHEN 2 THEN N'推推推推推推推推推推推推，沒人回我就再貼一次。'
        ELSE N'衝人氣衝人氣，路過幫回，這篇沒內容也要一起頂上去。' END END,
    CASE WHEN u.Ordinal<=12 THEN N'RESOLVED' WHEN u.Ordinal<=20 THEN N'PENDING' ELSE N'REJECTED' END,
    DATEADD(minute,-u.Ordinal*20,CONVERT(datetime2(3),'2026-10-02T03:00:00'))
FROM @demoUsers u JOIN @demoUsers reporter ON reporter.Ordinal=u.Ordinal%24+1;

INSERT social.SocialPosts(Id,BoardCode,UserId,PostType,PublisherType,ContentMode,Title,Content,Status,CreatedAt,UpdatedAt)
SELECT PostId,N'GENERAL',AuthorId,N'POST',N'COMMUNITY',N'CUSTOM',Title,Content,
    CASE WHEN ReportStatus=N'RESOLVED' THEN N'HIDDEN' ELSE N'PUBLISHED' END,CreatedAt,
    CASE WHEN ReportStatus=N'RESOLVED' THEN DATEADD(minute,15,CreatedAt) ELSE CreatedAt END
FROM @moderationCases c WHERE NOT EXISTS(SELECT 1 FROM social.SocialPosts p WHERE p.Id=c.PostId);

INSERT social.ContentReports(Id,ReporterUserId,TargetType,TargetId,Reason,Detail,Status,Resolution,ReviewedByUserId,ReviewedAt,CreatedAt,IsAutoGenerated)
SELECT ReportId,ReporterId,N'POST',PostId,N'SPAM',
    CASE WHEN ReportStatus=N'REJECTED' THEN N'這篇是不是在洗版？想請管理員確認。' ELSE N'內容一直重複，跟文物討論也沒什麼關係。' END,
    ReportStatus,CASE ReportStatus WHEN N'RESOLVED' THEN N'確認為重複宣傳或無意義洗版，已隱藏貼文。' WHEN N'REJECTED' THEN N'內容為正常提問，未發現洗版情形，保留貼文。' END,
    CASE WHEN ReportStatus<>N'PENDING' THEN (SELECT UserId FROM @demoUsers WHERE Ordinal=1) END,
    CASE WHEN ReportStatus<>N'PENDING' THEN DATEADD(minute,15,CreatedAt) END,DATEADD(minute,3,CreatedAt),0
FROM @moderationCases c WHERE NOT EXISTS(SELECT 1 FROM social.ContentReports r WHERE r.Id=c.ReportId);

IF EXISTS(SELECT 1 FROM @moderationCases c JOIN social.ContentReports r ON r.Id=c.ReportId JOIN social.SocialPosts p ON p.Id=r.TargetId
    WHERE r.TargetType<>N'POST' OR r.ReporterUserId=p.UserId OR r.CreatedAt<p.CreatedAt
    OR (r.Status=N'PENDING' AND (r.ReviewedAt IS NOT NULL OR r.ReviewedByUserId IS NOT NULL))
    OR (r.Status<>N'PENDING' AND (r.ReviewedAt<r.CreatedAt OR r.ReviewedByUserId IS NULL OR r.Resolution IS NULL)))
    THROW 51000,N'審核情境的作者、檢舉或處理時間不一致。',1;
